@startuml

class DatiCondivisi{
    	/'Indica le vasche presenti'/
  	 	-Vector vasche

    	/'Indica il numero massimo di vasche che si possono posizionare in orizzontale'/
  	  	-int width

    	/'Indica il numero massimo di vasche che si possono posizionare in verticale'/
  	  	-int height


   	 	+getVasca(int id)



    	/'Metodo che permette di reimpostare tutti gli attributi ai valori iniziali'/
   	 	+reset()

    	/'Metodo che permette di aggiungere una vasca specificando la sua posizione'/
   	 	+aggiungiVasca(posizione pos)

    	/'Metodo che permette di spostare una vasca specificando quale vasca deve essere spostata e la sua nuova posizione'/ 
   	 	+spostaVasca(int id, posizione pos)

    	/'Metodo che permette rimuovere una vasca specificando 
    	quale vasca va rimossa'/
   	 	+rimuoviVasca(int id)
}


classVasca{

	/'Inclinazione della vasca'/
   	 	-float inclinazioneX

    	/'Indica la profondità della vasca'/
   	 	-float profondita

    	/'Indica l’acqua presente nella vasca'/
   	 	-Acqua acquaPresente

    	/'Rappresenta la barca presente nella vasca'/
    		-Barca barca


    	/'Indica la posizione della vasca nel piano di gioco'/
   	 	-posizione posizioneVasca
	

    	/'Metodo che permette di visualizzare la vasca visualizzando anche l’acqua e la barca'/
    		+visualizzaVasca()
		
		+setInclinazioneX();
    	/'Metodo che permette di simulare un movimento  
    	della scatola richiamando aggiornamento Acqua, poi aggiornamento Pallina e 
    	successivamento visualizzazione Vasca'/
    		+muovi()


    	/'Metodo che permette di aggiornare la posizione della barca all'interno della scatola
    	a seconda della velocità dell’acqua'/
   	 	+aggiornaPosBarca()

   	/'Metodo che permette di aggiornare l'altezza e la velocità dell’acqua 
    	nella parte destra e sinistra della vasca in base ai gradi di inclinazione di essa'/
    		+aggiornaDistribuzioneVelocitaAcqua()
}

class thRefresh{
    	

}

class thVasca{
    	

}


class Acqua{
    	/'Indica il valore di altezza della acqua nella parte sinistra della scatola'/
  	 	-float altezzaSx

    	/'Indica il valore di altezza della acqua nella parte destra della scatola'/
    		-float altezzaDx

    	/'Indica la velocita' dell’acqua/
   	 	-float velocitaDiSpostamento

    	/'Indica la quantita' di acqua presente nella vasca'/
    		-Color quantita

	/’In base alla profondità c’è un diverso colore dell’acqua nella vasca'/
  	 	-float profondità 



    	/'Metodo che permette di aggiornare l'inclinazione dell’acqua
     dell'altezza di destra e di sinistra della scatola passati come parametro'/
    		+aggiorna(float altezzaDx, float altezzaSx)

    	/'Metodo che permette di visualizzare l’Acqua/
   		+visualizzaAcqua()

    	/'Metodo che permette di reimpostare tutti gli attributi ai valori iniziali'/
    		+reset()

}

class Barca{
    	/'Indica la posizione nella vasca dove e' presente la barca'/
		-Point pos
	/' Indeica la dimensione della barca dimensione*dimensione'/
		-float dimensione
   	/'Indica il colore della barca'/
   	 	-String colore

    	/'Indica le dimensioni della barca'/
   	 	-float dimensioni

    	/'Indica la velocita' di spostamento della barca se e' in movimento'/
    		-float velocitaDiSpostamento

    	/'Indica se la barca e' visibile e soprattutto presente nella scatola'/
    		-boolean BarcaPresente



    	/'Metodo che visualizza la barca/
   	 	+visualizza()

    	/'Metodo che rimuove la barca/
    		+rimuovi()

  	 /'Metodo che sposta la barca nella vasca'/
   		 +sposta(Point a)

    	/'Metodo che permette di reimpostare tutti gli attributi ai valori iniziali'/
   		 +reset()
}




class Input{
	/'Rappresenta il valore di input letto dalla tastiera scrivi a inclina sx scrivi d inclina dx'/
		-Character inputTastiera


	/'Rappresenta i valori di input letto dall'accelerometro'/
		-int AccX
		-int AccY

	/'Rappresenta il valore di input letto dal dispositivo'/
		-int dispositivo


	/'Metodo che permette di leggere il valore di input dalla tastiera e aggiornare
	di conseguenza l'attributo “inputTastiera” della classe'/
		+leggiDaTastiera()

}
@enduml


